# Generated by Django 2.2.6 on 2020-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='niranguser',
            name='mobile',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
