# Generated by Django 2.2.6 on 2020-10-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201011_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niranguser',
            name='mobile',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
