# Generated by Django 2.2.6 on 2020-10-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201011_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='niranguser',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='niranguser',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='niranguser',
            name='mobile',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
